spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/lkx?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: Zgg@1996
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package: com.example.lkx.pojo
  configuration:
    map-underscore-to-camel-case: true